#!/bin/sh

TEST_DIR=`dirname ${BASH_SOURCE[0]}`

cd ${TEST_DIR}/..

npm install

echo ''
echo 'Testing pac generated by FloraPacNJS'
node ${TEST_DIR}/performanceTest.js ${TEST_DIR}/flora.pac

echo ''
echo 'Testing pac generated by gfwlist2pac'
node ${TEST_DIR}/performanceTest.js ${TEST_DIR}/gfwlist2pac.pac

echo ''
echo 'Testing pac generated by switchysharp'
node ${TEST_DIR}/performanceTest.js ${TEST_DIR}/switchysharp.pac

echo ''
echo 'Test end'