#!/bin/sh

cd `dirname ${BASH_SOURCE[0]}`

npm install

echo ''
echo 'Testing pac generated by FloraPacNJS'
node ./performanceTest.js ./flora.pac

echo ''
echo 'Testing pac generated by gfwlist2pac'
node ./performanceTest.js ./gfwlist2pac.pac

echo ''
echo 'Testing pac generated by switchysharp'
node ./performanceTest.js ./switchysharp.pac

echo ''
echo 'Test end'